language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
before_install:
- make install
services:
- mongodb
script:
- make test
after_success:
- codecov
env:
  global:
  - secure: hI3T7Ey8X/2OCKdwCnUy1yBPnfNtpsIny8dLPY7GksXnxtAHUHdyDfOD9hhfDA7rIXtyArZT+6rjK0EB4UKmwzn9QohZN0spYRoXwzxTq8DRst2O6DJDJtodyJ23ZtZOmoxvzD93MPa57zcfWhYuYgJx3Cn3M1ns8GQz8iUpnSXSiECC/P8D/k2rNwqvrC4gLMDaygGdvcLOt+T19MwmkUpkSd7Jna9jzN4G+0CKofxOEmd3RJPphAZuMDu9se5gAN8fWzd5uci+S8UU1eae/HxBNmirpbCXDPiZfYxw2u4aWaVQggN7xLz8ft1EcW+f2wqzgo66BtZUbNyS7MakDShSC9AxgLFI0p/5hKNzemckiMjtiMWfchweCeuEJepwGnfm4bKpok+0/zHp8MUhz0xPtdE/IOwqHCVwgs1jRyaTsvafOTfDtDsjn3gHNKOX22UgwkPila8A/sjp/GwL+CRv9ZITapkWGFC118yljKfuTAps5cIwSiwOrTmCdgCfIKYPoJ0ocNGsG8OLfRFbqNoulhomkaUqmtcjQNo7oxsvnBw/wB6hvE2lxXB0DmzbhtOiBUW/xRgwhxAiwIsw9iAuwmX3NJ3Qv3bN+b0pNfitDTxtedctRQsgP5GpCavKKJ6ryUQ+NEj49qjwsTOVmsdo/AOw+4XK8cuL42tn41c=
  - secure: lSfA8bvkDSt0X9ilnJne3gO1YfdYqzG89sNUMrFSDdYYkx9TcBeHyp5t4UNaJMUoRy2Pb88DBt/UreALmVzFVfaeqlhuT47rMuyzdaIXAVePQB/AZJ2KtIN2tiFsaZ4wBVjCus8LOWr4BNPay4P8EtkozJFvyRF8X3OEEysnd+mR8+1XzuWnD1nmGkc73PM/L1oEqzNXapHM7hDTKNH5xZryRnfKjfYVBZaOspM91hfESc7+bPmppmH6V8CEvW+pOV5Xby929dwkGxYhjJb7G5FEdhDqIDFkqS87LvULPDszDFjS3/Fnhss8jap9QrlWsiHlUImEQLJ9+8YYW9TtG0YuXT3BhRDLs8nHnDUi/ttRc+n4OX1mozhzOYmYD5MbBDzvTPQRgIHj1IgK7uYVKXuQ9Flsknjp6zIZoxef0lWyO+Y1XGgJiomOj5MvBoL7TkpsQMEkzhYh9N+pGvR8l/kmxgsr3hqtJltW3ADVcbRtM5GfNXzRnzkjt8JkYOj2U1uk1KE8nT+apBNxmFZDRYzZoGQB4LQf+u9dF2oqAZqtIkDdur//mSirfEn8e2m68WAfgOpqld5Erf+rTCgtlo4p8VDr41Cp8PKDsTN0dzelbY6qVcw0TAU226PpfoqlfyGbrzNvOkGgiUjsWN680LrI2d6l20IbQ9uFRtfIU64=
  - secure: JHTsVgPcbii6nAN5VkpEPOqraN256M/qOYyGO0QvZLQ+oij4k1Lakw2+BP6zW6BToyDE7SJbhkZo3eUJxaRO9+nG5gYnosWVG31XmDr72hDEgJZzhNgP2nH14ReilzmL/FRX4bTT6v7idZEGZhZoVK2HzVHDPzoMVoq4jgs2kLEJY061DWcSomx4QOMmfN2flRdhVV4rpfO6SEWYEISxc7T5FEBe8sh4O4TTzMUU25mF5FTA3hP/ye2hluMu9H6TgHpkfKnet1thECAE3bsZSw26nztWW9n/j6JuaFYN3ISXlJfuh7/qdcmAKCUR0Mb64ZimnO/+1tUVRKWFmc/TqWOMbeJ82++c2xitmbFmdExS113m6M5Rx4AHUOUDpcaLQzhpG6GgR4MAXl3qMsmTEktT5D/veR7jjzcMvhKNbVf+OpMF2ix5Q9Jy797MCpEI1Pp9IlCcfMLkQd7MhcICBYXvzEj/gTgszcmCUYqdEytKZJsmtuvJI7paKydopdpKGA1gy3RQB4EnNw5uvQH9TK1KQAYDSAcLzAiL/qNuOlOE/a7OeUeA79UubzF4WScvTb5imZkZwE3i+GFwy5iEqkVqjI8Z6heqPoUbr4LRqeyn6drXriKCqL7JKl0O3cHcRNAhn/xA8/IXrEtKk9G/j8ietYB4t5ZifeI6eM7wtRo=
