version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mongo:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: make install
      - run:
          name: Run tests.
          command: make test
machine:
  services:
    - mongodb
    - postgresql