version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mongo:latest
      - image: circleci/postgres:latest
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: make install
      - run:
          name: Prueba PostgreSQL
          command: docker run -e POSTGRES_PASSWORD=$POSTGRES_PSWD -d postgres:latest
      - run:
          name: Run tests.
          command: make test
machine:
  services:
    - mongodb